public class DiscussionCont {
//test
    public DiscussionCont(ApexPages.StandardController controller) {
    
    }
   /* public Attachment attachment{
    	get{
    		if(attachment == null)
    		attachment = new Attachment();
    		return attachment;
    	}
    	set;
    }
    public void save_attachment(){
    	DiscussionBook__c dis = [Select id from DiscussionBook__c limit 1];
    	attachment.ParentId = dis.Id;
    	insert attachment;
    	    }*/

}